version: '2'
services:
  kmpbuild:
    container_name:           kmpbuild
    build:
      context:                context
      dockerfile:             Dockerfile
    environment:
      DEBUGAUTOEXECJOBS: 'TRUE'
    volumes:
      - ./bindir:/bindirxx
    command: bash -c 'cp /bindir/* /bindirxx'
    # command: tail -f /dev/null
